genres = ['adventure', 'action', 'rpg', 'shooter', 'puzzle', 'fighting', 'rythm', 'visual-novel', 'strategy', 'sports', 'platform', 'metroidvania', 'simulation', 'multiplayer', 'racing']

games = [['adventure', 'Okami', '93', 'PS2 +m', '2006'],
		 ['action', 'Sekiro', '91', 'XOne +m' '2019'],
		 ['rpg', 'The Elder Scrolls V: Skyrim', '96', 'X360 +m', '2011'],
		 ['shooter', 'Doom Eternal', '88', 'PC +m', '2020'],
		 ['puzzle', 'Picross 3D', '83', 'NDS', '2010'],
		 ['fighting', 'Super Smash Bros. Melee', '92', 'GC', '2001'],
		 ['rythm', ],
		 ['visual-novel', ],
		 ['strategy', ],
		 ['platform', ],
		 ['sports', ],
		 ['metroidvania', ],
		 ['simulation', ],
		 ['multiplayer', ],
		 ['racing', ],
		 ['adventure', ],
		 ['action', ],
		 ['rpg', ],
		 ['shooter', 'Gears of War', '94', 'X360', '2006'],
		 ['puzzle', 'World of Goo', '94', 'Wii +m', '2008'],
		 ['fighting', 'Dragon Ball FighterZ', '87', 'PS4 +m', '2018'],
		 ['rythm', ],
		 ['visual-novel', ],
		 ['strategy', ],
		 ['platform', ],
		 ['sports', ],
		 ['metroidvania', ],
		 ['simulation', ],
		 ['multiplayer', ],
		 ['racing', ],
		 ['adventure', ],
		 ['action', ],
		 ['rpg', ],
		 ['rpg', ],
		 ['shooter', ],
		 ['adventure', ],
		 ['multiplayer', ],
		 ['strategy', ],
		 ['action', ],
		 ['rpg', ]]