genres = ['adventure', 'action', 'rpg', 'shooter', 'puzzle', 'fighting', 'rythm', 'visual-novel', 'strategy', 'sports', 'platform', 'metroidvania', 'simulation', 'multiplayer', 'racing']

games = [['adventure', 'Okami', '93', 'PS2 +m', '2006'],
		 ['action', 'Sekiro', '91', 'XOne +m', '2019'],
		 ['rpg', 'The Elder Scrolls V: Skyrim', '96', 'X360 +m', '2011'],
		 ['shooter', 'Doom Eternal', '88', 'PC +m', '2020'],
		 ['puzzle', 'Picross 3D', '83', 'NDS', '2010'],
		 ['fighting', 'Super Smash Bros. Melee', '92', 'GC', '2001'],
		 ['rythm', 'Sayonara Wild Hearts', '88', 'iOS', '2019'],
		 ['visual-novel', 'Steins;Gate', '87', 'PC +m', '2014'],
		 ['strategy', 'Fire Emblem: Awakening', '92', '3DS', '2013'],
		 ['platform', 'Rayman Legends', '92', 'Wii U +m', '2013'],
		 ['sports', 'Winning Eleven: Pro Evolution Soccer 2007', '82', 'PS2 +m', '2007'],
		 ['metroidvania', 'Metroid Dread', '88', 'NSW', '2021'],
		 ['simulation', 'The Sims 3', '86', 'PC', '2009'],
		 ['multiplayer', 'Pokémon Unite', '70', 'NSW +m', '2021'],
		 ['racing', 'Gran Turismo 7', '87', 'PS5', '2022'],
		 ['adventure', 'Minecraft', '93', 'PC +m', '2011'],
		 ['action', 'Tomb Raider', '87', 'PS3 +m', '2013'],
		 ['rpg', 'Final Fantasy VII Remake Intergrade', '89', 'PS5 +m', '2021'],
		 ['shooter', 'Gears of War', '94', 'X360', '2006'],
		 ['puzzle', 'World of Goo', '94', 'Wii +m', '2008'],
		 ['fighting', 'Dragon Ball FighterZ', '87', 'PS4 +m', '2018'],
		 ['rythm', 'Guitar Hero', '91', 'PS2', '2005'],
		 ['visual-novel', 'Zero Escape: Virtue\'s Last Reward', '88', '3DS +m', '2012'],
		 ['strategy', 'Advance Wars', '92', 'GBA', '2001'],
		 ['platform', 'Super Mario Odyssey', '97', 'NSW', '2017'],
		 ['sports', 'Virtua Tennis', '92', 'DrC', '2000'],
		 ['metroidvania', 'Castlevania: Symphony of the Night', '93', 'PSOne', '1997'],
		 ['simulation', 'Game Dev Story', '86', 'iOS', '2010'],
		 ['multiplayer', 'World of Warcraft', '93', 'PC', '2004'],
		 ['racing', 'Mario Kart 8 Deluxe', '92', 'NSW', '2017'],
		 ['adventure', 'The Legend of Zelda: The Wind Waker', '96', 'GC', '2003'],
		 ['action', 'NieR: Automata - Become As Gods Edition', '90', 'XOne +m', '2018'],
		 ['rpg', 'The Legend of Heroes: Trails of Cold Steel II', '90', 'PS3 +m', '2016'],
		 ['rpg', 'Dragon Quest XI S: Echoes of an Elusive Age - Definitive Edition', '92', 'XOne +m', '2020'],
		 ['shooter', 'Splatoon 2', '83', 'NSW', '2017'],
		 ['adventure', 'Elden Ring', '96', 'XsX', '2022'],
		 ['multiplayer', 'Tetris 99', '83', 'NSW', '2019'],
		 ['strategy', 'Sid Meier\'s Civilization VI', '88', 'PC +m', '2016'],
		 ['action', 'Gravity Rush', '83', 'PSVita', '2012'],
		 ['rpg', 'Divinity: Original Sin II', '93', 'PC', '2017']]

def add_game(genre, title, score = 'XX' , platform = 'n/a', year = 'n/a'):
	games.append([genre, title, score, platform, year])

