genres = ['adventure', 'action', 'rpg', 'shooter', 'puzzle', 'fighting', 'rythm', 'visual-novel', 'strategy', 'sports', 'platform', 'metroidvania', 'simulation', 'multiplayer', 'racing']

games = [['adventure', 'Okami', '93', 'PS2 +m', '2006'],
		 ['action', 'Sekiro', '91', 'XOne +m' '2019'],
		 ['rpg', 'The Elder Scrolls V: Skyrim', '96', 'X360 +m', '2011'],
		 ['shooter', 'Doom Eternal', '88', 'PC +m', '2020'],
		 ['puzzle', 'Picross 3D', '83', 'NDS', '2010'],
		 ['fighting', 'Super Smash Bros. Melee', '92', 'GC', '2001'],
		 ['rythm', ],
		 ['visual-novel', 'Steins;Gate', '87', 'PC +m', '2014'],
		 ['strategy', 'Fire Emblem: Awakening', '92', '3DS', '2013'],
		 ['platform', 'Rayman Legends', '92', 'Wii U +m', '2013'],
		 ['sports', 'Winning Eleven: Pro Evolution Soccer 2007', '82', 'PS2 +m', '2007'],
		 ['metroidvania', 'Metroid Dread', '88', 'NSW', '2021'],
		 ['simulation', 'The Sims 3', '86', 'PC', '2009'],
		 ['multiplayer', ],
		 ['racing', ],
		 ['adventure', ],
		 ['action', ],
		 ['rpg', ],
		 ['shooter', 'Gears of War', '94', 'X360', '2006'],
		 ['puzzle', 'World of Goo', '94', 'Wii +m', '2008'],
		 ['fighting', 'Dragon Ball FighterZ', '87', 'PS4 +m', '2018'],
		 ['rythm', ],
		 ['visual-novel', 'Zero Escape: Virtue\'s Last Reward', '88', '3DS +m', '2012'],
		 ['strategy', 'Advance Wars', '92', 'GBA', '2001'],
		 ['platform', 'Super Mario Odyssey', '97', 'NSW', '2017'],
		 ['sports', 'Virtua Tennis', '92', 'DrC', '2000'],
		 ['metroidvania', 'Castlevania: Symphony of the Night', 'PSOne', '1997'],
		 ['simulation', 'Game Dev Story', '86', 'iOS', '2010'],
		 ['multiplayer', ],
		 ['racing', ],
		 ['adventure', ],
		 ['action', ],
		 ['rpg', ],
		 ['rpg', ],
		 ['shooter', ],
		 ['adventure', ],
		 ['multiplayer', ],
		 ['strategy', ],
		 ['action', ],
		 ['rpg', ]]